name: makewaves
channels:
- conda-forge
dependencies:
- h5py
- matplotlib
- numpy
- pandas
- pyqt=5
- python=3
- pywin32
- pip
- qt
- pip:
  - git+https://github.com/petebachant/daqmx.git
  - pythonqwt
  - pyqt5-tools
