name: makewaves
channels:
- conda-forge
dependencies:
- h5py
- numpy
- pandas
- pyqt=5
- python=3
- pywin32
- pip
- qt
- pip:
  - https://github.com/petebachant/daqmx/archive/refs/heads/master.zip
  - pythonqwt
